// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaqlizlxchgdwzakclqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhcWxpemx4Y2hnZHd6YWtjbHFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDY3NTksImV4cCI6MjA3MDgyMjc1OX0.ErR9c57gjaoNFuvZ5RykI8C6lpID4UDQHv-P5Dl8KGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});